version: "2.19"

services:
    lava:
        build: Lavalink/
        
        ports:
            - "2333:2333"
        
        command: java -jar Lavalink.jar
        
    command_handler:
        build: QM/
        
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - LAVALINK_IP=${LAVALINK_PORT}
            - LAVALINK_PORT=${LAVALINK_PORT}
            
        volumes:
            - db-tracks:/DB
        
        command: dotnet QM.dll
        
        depends_on:
            - lava
            
volumes:
    db-tracks:
    
 
 
