version: "3.8"

services:
    lava:
        build: Lavalink/
        hostname: lava
        
        networks:
            - lavalink
        
        ports:
            - "2333:2333"
        
    command-handler:
        build: QM/
        
        networks:
            - lavalink
        
        environment:
            - LAVALINK_IP=${LAVALINK_IP}
            - LAVALINK_PORT=${LAVALINK_PORT}
            
        volumes:
            - db-tracks:/DB
        
        depends_on:
            - lava
            
volumes:
    db-tracks:
    
networks:
    lavalink:
        name: lavalink 
