version: "3.8"

services:
    lava:
        build: Lavalink/
        hostname: lava
        
        environment:
            SERVER_ADDRESS: 0.0.0.0
            SERVER_PORT: ${LAVALINK_PORT}
            LAVALINK_PASSWORD: ${LAVALINK_PASSWORD}

        networks:
            - lavalink
        
        ports:
            - 2333:2333
    
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}

        ports:
            - 5432:5432

        volumes:
            - db-tracks:/var/lib/postgresql/data

        networks:
            - db

    command-handler:
        build: QM/
        
        networks:
            - lavalink
            - db
        
        environment:
            LAVALINK_PORT: ${LAVALINK_PORT}
            LAVALINK_PASSWORD: ${LAVALINK_PASSWORD}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
                  
        depends_on:
            - lava
            - db
            
volumes:
    db-tracks:
    
networks:
    lavalink:
        name: lavalink 
    db:
        name: postgresdb
